apiVersion: v1
kind: Namespace
metadata:
  name: poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-2
  namespace: projectcontour
spec:
  selector:
    matchLabels:
      app: demo-2
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-2
    spec:
      containers:
        - name: demo
          env:
            - name: APP_NAME
              value: "Demo App 2"
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service-2
  namespace: projectcontour
spec:
  type: ClusterIP
  selector:
    app: demo-2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-gateway
  namespace: projectcontour
spec:
  gatewayClassName: contour
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-http-route
  namespace: projectcontour
spec:
  parentRefs:
    - name: demo-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /coiso/
      backendRefs:
        - name: demo-service-2
          port: 80
          weight: 1
